spring.mongodb.uri=mongodb+srv://achintya26022006_db_user:G3HhIjCHODkJP0OA@cluster0.oeayxyx.mongodb.net/eexchange?retryWrites=true&w=majority
spring.mongodb.auto-index-creation=true
app.secret.key=oerfiq4fi3wefu3b4gf9734fb3bf34g45g435t452y65243qt42t24q35tfewrgvdvbdfrbrbwmuym678k678i5


# Email Configuration (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=achintya11022006@gmail.com
spring.mail.password=qcby ccmx gptb hhax
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true